### PR TITLE
Added Uyghur language support

### PR DESCRIPTION
**Pull request by abduwaly**

### CODE REVIEW

**Comment by abduwaly** [comment]
Hi @funkyremi , I added Uyghur language inside `language.js` as Uyghur language was already supported by Google Translate now. Please help review 🙏

**Comment by funkyremi** [comment]
Thanks for the PR :-)

**Comment by funkyremi** [comment]
Version 1.4.4 is now available 👌

**Comment by abduwaly** [comment]
Thanks for the quick response 👍 
But seems like 'ug' is not yet supported by the API, let me investigate further then get back to this.

Screen Shot 2020-05-09 at 8 11 01 PM

**Pull request merged**
