### PR TITLE
Add a hotfix for 403 error

### PR DESCRIPTION
**Pull request by oshliaer**
This is a simple attempt to get the application back into working state.
As I understand the 403 error is always returned now.

It seems the main library have to migrate to latest batch-style RPC API
https://github.com/vitalets/google-translate-api/pull/61

#46

### CODE REVIEW

**Comment by oshliaer** [comment]
@funkyremi can you help me test proxies?

**Comment by funkyremi** [comment]
Thanks :-) I fixed the proxy.

**Comment by vkedwardli** [comment]
The pull request https://github.com/vitalets/google-translate-api/pull/61 is merged, it would be better to use the fork directly

**Comment by funkyremi** [comment]
Yes @vkedwardli I'll do it for the next release. Thanks

**Pull request merged**
