### PR TITLE
Translate line feature

### PR DESCRIPTION
**Pull request by oshliaer**
Hi! I'd like to add a feature.

It's helping me to translate *.md files line-per-line. It's really helpful.

Please consider this PR.

### CODE REVIEW

**Comment by funkyremi** [comment]
Thanks for the PR 👌 It looks nice!

Here are few things that should be edited before merging it:

- Add another command that asks for which language (for those who don't have preferred language).
- Remove your demo2.gif as it's not used.
- Can you document previous functions in the code like you made with yours?
- Add a small description of the new feature in the readme

**Comment by oshliaer** [comment]
- [x] Add another command that asks for which language (for those who don't have preferred language).
- [x] Remove your demo2.gif as it's not used.
- [x] Can you document previous functions in the code like you made with yours?
- [x] Add a small description of the new feature in the readme

**Comment by oshliaer** [comment]
@funkyremi check it again, please.

**Comment by funkyremi** [comment]
Perfect thank you! It's live now.

**Comment by oshliaer** [comment]
@funkyremi! :fireworks: 

Thank you too. It's really good extension!

**Pull request merged**
