### PR TITLE
Translate Text Not Separated By Spaces

### PR DESCRIPTION
**Pull request by Brian-Bartels**
This used the Npm package humanize to turn text that is separated by spaces into human readable text.
"fooBarBaz" => "Foo bar baz"
"foo_bar_baz" => "Foo bar baz"

And then it translates it and recombines it to camel case. this is a KNOWN ISSUE, if you have foo_bar_baz you will end up with fooBarBaz. I feel like this is an acceptable limitation. I could consider contributing to the humanize package. It would be awesome if it gave you a return value that represented the separation style so that we could translate and then replace with the appropriate casing.

### CODE REVIEW

**Comment by Brian-Bartels** [comment]
I made this PR before completing the other one since it's so much smaller and independent. I have the bigger comment hover one sitting on deck though! I'll open that PR once the first one that I opened is closed :)

**Comment by Brian-Bartels** [comment]
#35

**Comment by Brian-Bartels** [comment]
giphy

**Comment by funkyremi** [comment]
Hi :-) I'll merge this PR after the conflicts are resolved. Thanks again

**Comment by Brian-Bartels** [comment]
Just double checked that the merge didn't break things. Seems to work well still

**Comment by funkyremi** [comment]
Also I'm wondering if it's a good idea to always translate camel case names. Sometimes you just want text to be translated and not variable names. Maybe it should be good to add a setting to decide whether or not to translate variable names. What do you think?

**Comment by Brian-Bartels** [comment]
So this will only kick in if the translation failed completely. So all the same translation behavior would still be the same. However, sometimes when translating things that result in no change whatsoever, this secondary translation attempt would kick in. I'm not sure if more settings would actually increase the usability, especially since settings are historically non-discoverable

**Comment by Brian-Bartels** [comment]
Example translations before this change:
"love peace life validateSelectionOfBoard" -> "amor paz vida validarSelectionOfBoard"
"validateSelectionOfBoard" -> "validateSelectionOfBoard" // no change at all

Example translations after this change:
"love peace life validateSelectionOfBoard" -> "amor paz vida validarSelectionOfBoard" // same as before
"validateSelectionOfBoard" -> "validarSelecciónDeTablero" // This is the new feature

**Comment by funkyremi** [comment]
Version 1.4.7 published :-) Thank you Brian!

**Pull request merged**
